// Code generated by github.com/ccheers/protoc-gen-checker. DO NOT EDIT.

package v1

import (
	fmt "fmt"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ccheers/protoc-gen-checker package it is being compiled against.

func (x *Test) Check() error {
	if !(x.U32 < 0) {
		return fmt.Errorf("u32 必须要大于\" 0 \"")
	}

	return nil
}
